In [ ]:
import numpy as np

In [ ]:
#Questions 1:
#Create a numpy array starting from 2 till 50 with a stepsize of 3.
arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [ ]:
#Questions 2:
#Accept two lists of 5 elements each from the user.
#Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

lst1 = [] 
lst2 = [] 

n = 5 
print("Enter 5 elements:")
for i in range(0, n): 
  ele = int(input()) 
  lst1.append(ele)
print("List 1 :", lst1) 

print("Enter 5 elements:")
for i in range(0, n): 
  ele = int(input()) 
  lst2.append(ele)
print("List 2:",lst2)   

arr1 = np.array(lst1)
arr2 = np.array(lst2)

arr3 = np.concatenate((arr1,arr2))
print("Concatenate Array",arr3)

print("Sorted Array",np.sort(arr3))





Enter 5 elements:
6
9
78
25
11
List 1 : [6, 9, 78, 25, 11]
Enter 5 elements:
56
89
4
0
30
List 2: [56, 89, 4, 0, 30]
Concatenate Array [ 6  9 78 25 11 56 89  4  0 30]
Sorted Array [ 0  4  6  9 11 25 30 56 78 89]


In [ ]:
#Questions 3:
#Write a code snippet to find the dimensions of a ndarray and its size.
def dimofarr(a):
  return a.ndim
def sizeofarr(a):
  return a.size

ndarr = np.arange(24).reshape((2, 3, 4))

print('numpy array:',ndarr)
print('dimensions of a array: ',dimofarr(ndarr))
print('size of the array:',sizeofarr(ndarr))

numpy array: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
dimensions of a array:  3
size of the array: 24


In [61]:
#Questions 4:
#How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
#Hint: np.newaxis, np.expand_dims
def arrayconvert(a):
  return  a[np.newaxis,]

arr1 = np.arange(50)
print('1D Array:',arr1)
print(arr1.shape)
arr2 = arrayconvert(arr1)
print('2D Converted Array:',arr2)
print(arr2.shape)


1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
(50,)
2D Converted Array: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]]
(1, 50)


In [67]:
#Questions 5:
#Consider two square numpy arrays. Stack them vertically and horizontally.
#Hint: Use vstack(), hstack()

a = np.arange(0,25).reshape(5,5)
b = np.arange(25,50).reshape(5,5)

print("Vertical stacking:\n", np.vstack((a, b))) 
print("\nHorizontal stacking:\n", np.hstack((a, b)))


Vertical stacking:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

Horizontal stacking:
 [[ 0  1  2  3  4 25 26 27 28 29]
 [ 5  6  7  8  9 30 31 32 33 34]
 [10 11 12 13 14 35 36 37 38 39]
 [15 16 17 18 19 40 41 42 43 44]
 [20 21 22 23 24 45 46 47 48 49]]


In [76]:
#Questions 6:
#How to get unique items and counts of unique items?

a = [1, 2, 2, 4, 3, 6, 8, 6, 4, 8, 121,33,11,8,9,7,5,62,32,1,2] 
print('list with duplicate values/items:',a)  
print('count of all items with duplicates:',np.size(a))
uni = np.unique(a) 
print('Unique Items:',uni)
print('count of total unique items:',uni.size)



list with duplicate values/items: [1, 2, 2, 4, 3, 6, 8, 6, 4, 8, 121, 33, 11, 8, 9, 7, 5, 62, 32, 1, 2]
count of all items with duplicates: 21
Unique Items: [  1   2   3   4   5   6   7   8   9  11  32  33  62 121]
count of total unique items: 14
